version: 1.0.{build}
image: Ubuntu1804
install:
- ps: >-
    npm install --loglevel=error


    "//registry.npmjs.org/:_authToken=`$`{npm_auth_token`}" | Out-File (Join-Path $ENV:APPVEYOR_BUILD_FOLDER ".npmrc") -Encoding UTF8
build:
  verbosity: minimal
after_deploy:
- ps: >-
    npm pack

    npm publish