# version: 1.0.{build}
# image: Ubuntu1804
# environment:
#   matrix:
#     - nodejs_version: STABLE
#       configuration: publish
#     - nodejs_version: LTS

# install:
# - ps: >-
#     npm install --loglevel=error

#     "//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | Out-File (Join-Path $ENV:APPVEYOR_BUILD_FOLDER ".npmrc") -Encoding UTF8

# before_build:
#   - node --version
#   - npm --version
#   - npm install -g typescript
#   - npm run build

# after_deploy:
# - ps: npm publish "src/Dnt.Npm"
