version: 1.0.{build}
image: Ubuntu1804
environment:
  matrix:
    - nodejs_version: STABLE
      configuration: publish
    - nodejs_version: LTS

install:
- ps: >-
    Install-Product node $env:nodejs_version
    npm install --loglevel=error

    "//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII

after_deploy:
- ps: npm publish "src/Dnt.Npm"
