name: Node.js Package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present

    # - name: Archive production artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: dist-without-markdown
    #     path: |
    #       dist
    #       !dist/**/*.md

    # - name: Archive code coverage results
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: code-coverage-report
    #     path: output/test/code-coverage.html

    # - name: Download all workflow run artifacts
    #   uses: actions/download-artifact@v2

    - name: Publish to NPMJS
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
